# This file contains all the valid fields with their default value. Default
# values are set by default, you should only have the changed values.

[color]
ui = "49;30"
cell = "49;39"
cell_over = "49;39;7;1"
cell_selected = "49;32"
ln_over = "49;32;7;1"
ln = "49;32"
sheet_ui = "49;39"
sheet_ui_over = "45;39;7;1"
sheet_ui_selected = "45;32"
ui_cell_text = "49;39;1"
insert = "49;39"

[window]
num_col_width = 5
col_width = 14
row_width = 1 # Other size is not supported
use_cell_color_for_sep = true
cell_l_sep = " "
cell_r_sep = " "

